### ISSUE TITLE
java.lang.RuntimeException: Error with phantomJS

### ISSUE THREAD

**Issue by markposterone** [sencha/gxt-demo-edash#9]
mvn install (on Windows 7) fails with something about phantom.js:

btw link "GXT Maven here." in readme file is not correct. 

D:\TEST\GXT4_EDASH\gxt-demo-edash-master>mvn install
[INFO] Scanning for projects...
[WARNING] The project com.sencha.gxt:gxt-edash:war:1.0.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin proje
cts but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.or
g/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Sencha GXT Executive Dashboard Demo Parent
[INFO] Sencha GXT Executive Dashboard Demo Theme
[INFO] Sencha GXT Executive Dashboard Demo
[INFO] Sencha GXT Executive Dashboard Demo Release Package
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Sencha GXT Executive Dashboard Demo Parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ gxt-edash-parent ---
[INFO] Installing D:\TEST\GXT4_EDASH\gxt-demo-edash-master\pom.xml to C:\Users\Blah\.m2\repository\com\sencha\gxt\gxt-edash-par
ent\1.0.0-SNAPSHOT\gxt-edash-parent-1.0.0-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Sencha GXT Executive Dashboard Demo Theme 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- phantomjs-maven-plugin:0.7:install (default) @ gxt-theme-edash ---
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (default) @ gxt-theme-edash ---
[INFO] Source directory: D:\TEST\GXT4_EDASH\gxt-demo-edash-master\com.sencha.gxt.theme.edash\target\generated-sources added.
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:add-resource (default) @ gxt-theme-edash ---
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (generate-theme) @ gxt-theme-edash ---
Downloading from codehaus-snapshots: http://nexus.codehaus.org/snapshots/com/sencha/gxt/gxt-themebuilder/4.0.3-SNAPSHOT/maven-meta
data.xml
[WARNING] Could not transfer metadata com.sencha.gxt:gxt-themebuilder:4.0.3-SNAPSHOT/maven-metadata.xml from/to codehaus-snapshots
 (http://nexus.codehaus.org/snapshots/): nexus.codehaus.org
Downloading from codehaus-snapshots: http://nexus.codehaus.org/snapshots/com/sencha/gxt/gxt/4.0.3-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.sencha.gxt:gxt:4.0.3-SNAPSHOT/maven-metadata.xml from/to codehaus-snapshots (http://nexu
s.codehaus.org/snapshots/): nexus.codehaus.org
template generation started
template generation complete
image generation started
generating icons
Win version: 0x1db10106 = 498139398 (Windows Vista)
Using custom image: D:\TEST\GXT4_EDASH\gxt-demo-edash-master\com.sencha.gxt.theme.edash\src\main\files\icons\button\toolBarArrow.p
ng
Using custom image: D:\TEST\GXT4_EDASH\gxt-demo-edash-master\com.sencha.gxt.theme.edash\src\main\files\icons\grid\collapse.png
Using custom image: D:\TEST\GXT4_EDASH\gxt-demo-edash-master\com.sencha.gxt.theme.edash\src\main\files\icons\grid\expand.png
Using custom image: D:\TEST\GXT4_EDASH\gxt-demo-edash-master\com.sencha.gxt.theme.edash\src\main\files\icons\menu\checked.png
Using custom image: D:\TEST\GXT4_EDASH\gxt-demo-edash-master\com.sencha.gxt.theme.edash\src\main\files\icons\menu\unchecked.png
image generation complete
compile started
bootstrap class path not set in conjunction with -source 1.7
Error on line -1 in null
compile complete
capture started
loading page D:/TEST/GXT4_EDASH/gxt-demo-edash-master/com.sencha.gxt.theme.edash/target/war/sliceme/index.html
Failed to load page

error with capture
java.lang.RuntimeException: Error with phantomJS:
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
        at com.sencha.gxt.themebuilder.ThemeSlicer.capture(ThemeSlicer.groovy:46)
        at com.sencha.gxt.themebuilder.ThemeSlicer$capture.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
        at com.sencha.gxt.themebuilder.ThemeBuilder$_main_closure6.doCall(ThemeBuilder.groovy:121)
        at com.sencha.gxt.themebuilder.ThemeBuilder$_main_closure6.doCall(ThemeBuilder.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
        at com.sencha.gxt.themebuilder.ThemeBuilder$__clinit__closure10.doCall(ThemeBuilder.groovy:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:914)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:897)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:166)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:572)
        at com.sencha.gxt.themebuilder.ThemeBuilder.main(ThemeBuilder.groovy:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:748)

**Comment by pedjapesic** [comment]
I had the same issue when I tried this last time. The only diff is that first time you start "mvn install" it fails with different error, then you try to "mvn clean" and you get some error, after that try again "mvn install" and there you go, something is wrong with some phantom.js. Is there any place where we can simply download this sources without any maven build like explorer examples that are included in gxt.jar (commercially licensed) distribution ?

**Comment by branflake2267** [comment]
I've found the issue with the sliceme/index.html path on Windows 10. There is a way around it, by turning off slicing, which adds support for browsers IE9 & IE10. 

Turn off slicing is an option: `-slicedDisabled false`
```
Y:\sdks\gxt\gxt-4.0.3\themebuilder\examples\quick-start>..\..\bin\themer.bat -slicedDisabled false quick-start.theme
```

In this case, add:
```
<argument>-slicedDisabled</argument>
<argument>false</argument>
```
![screen shot 2018-07-30 at 10 18 52 pm](https://user-images.githubusercontent.com/1326504/43439142-91884216-9446-11e8-9d87-c62ebaccb30f.png)
